; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=inject-tli-mappings -S -mcpu=gfx1250 -mtriple=amdgcn-amd-amdhsa  -vector-library=AMDGCNLIB  -o - %s | FileCheck %s
target triple = "amdgcn-amd-amdhsa"

define amdgpu_kernel void @test_with_wmma( ptr addrspace(1) %input, ptr addrspace(1) %output, float %scaled_max, <16 x i32> %A, <16 x i32> %B, i32 %scale_idx) {
entry:

  %in0 = load float, ptr addrspace(1) %input, align 4
  %ptr1 = getelementptr float, ptr addrspace(1) %input, i64 1
  %in1 = load float, ptr addrspace(1) %ptr1, align 4

  %mul0 = fmul contract float %in0, 0x3FC0527DC0000000
  %mul1 = fmul contract float %in1, 0x3FC0527DC0000000

  %sub0 = fsub contract float %mul0, %scaled_max
  %sub1 = fsub contract float %mul1, %scaled_max
; CHECK: %exp0 = tail call float @llvm.amdgcn.exp2.f32(float %{{.*}}) #[[EXPF:[0-9]+]]
; CHECK-NEXT: %exp1 = tail call float @llvm.amdgcn.exp2.f32(float %{{.*}}) #[[EXPF:[0-9]+]]
  %exp0 = tail call float @llvm.amdgcn.exp2.f32(float %sub0)
  %exp1 = tail call float @llvm.amdgcn.exp2.f32(float %sub1)

  %vec0 = insertelement <2 x float> poison, float %exp0, i64 0
  %vec1 = insertelement <2 x float> %vec0, float %exp1, i64 1

  %vec_i32 = bitcast <2 x float> %vec1 to <2 x i32>

  %scale0 = extractelement <2 x i32> %vec_i32, i64 0
  %scale1 = extractelement <2 x i32> %vec_i32, i64 1

  %wmma0 = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(
  i32 0, <16 x i32> %A, i32 0, <16 x i32> %B, i16 0, <8 x float> zeroinitializer,
  i32 0, i32 0, i32 %scale0, i32 0, i32 0, i32 %scale_idx, i1 false, i1 false)

  %wmma1 = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(
  i32 0, <16 x i32> %A, i32 0, <16 x i32> %B, i16 0, <8 x float> %wmma0,
  i32 0, i32 0, i32 %scale1, i32 0, i32 0, i32 %scale_idx, i1 false, i1 false)

  store <8 x float> %wmma1, ptr addrspace(1) %output, align 32
  ret void
}

define amdgpu_kernel void @test_amdgcn_exp_log(ptr addrspace(1) %input, ptr addrspace(1) %scales, ptr addrspace(1) %output) {
entry:
  %in0 = load float, ptr addrspace(1) %input, align 4
  %ptr1 = getelementptr float, ptr addrspace(1) %input, i64 1
  %in1 = load float, ptr addrspace(1) %ptr1, align 4
  %scale0 = load float, ptr addrspace(1) %scales, align 4
  %sptr1 = getelementptr float, ptr addrspace(1) %scales, i64 1
  %scale1 = load float, ptr addrspace(1) %sptr1, align 4
  %mul0 = fmul contract float %in0, 0x3FC0527DC0000000
  %mul1 = fmul contract float %in1, 0x3FC0527DC0000000
  %sub0 = fsub contract float %mul0, %scale0
  %sub1 = fsub contract float %mul1, %scale1
; CHECK: %exp0 = tail call float @llvm.amdgcn.exp2.f32(float %{{.*}}) #[[EXPF:[0-9]+]]
  %exp0 = tail call float @llvm.amdgcn.exp2.f32(float %sub0)
; CHECK-NEXT: %log0 = tail call float @llvm.amdgcn.log.f32(float %{{.*}}) #[[LOGF:[0-9]+]]
  %log0 = tail call float @llvm.amdgcn.log.f32(float %exp0)
; CHECK-NEXT: %exp1 = tail call float @llvm.amdgcn.exp2.f32(float %{{.*}}) #[[EXPF:[0-9]+]]
  %exp1 = tail call float @llvm.amdgcn.exp2.f32(float %sub1)
; CHECK-NEXT: %log1 = tail call float @llvm.amdgcn.log.f32(float %{{.*}}) #[[LOGF:[0-9]+]]
  %log1 = tail call float @llvm.amdgcn.log.f32(float %exp1)
  %sum = fadd fast float %log0, %log1
  store float %sum, ptr addrspace(1) %output, align 4
  ret void
}

define amdgpu_kernel void @test_amdgcn_exp_f16(ptr addrspace(1) %input, ptr addrspace(1) %scales, ptr addrspace(1) %output) {
entry:
  %in0 = load half, ptr addrspace(1) %input, align 2
  %ptr1 = getelementptr half, ptr addrspace(1) %input, i64 1
  %in1 = load half, ptr addrspace(1) %ptr1, align 2
  %scale0 = load half, ptr addrspace(1) %scales, align 2
  %sptr1 = getelementptr half, ptr addrspace(1) %scales, i64 1
  %scale1 = load half, ptr addrspace(1) %sptr1, align 2
  %mul0 = fmul contract half %in0, 0xH3E14
  %mul1 = fmul contract half %in1, 0xH3E14
  %sub0 = fsub contract half %mul0, %scale0
  %sub1 = fsub contract half %mul1, %scale1
; CHECK: %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %{{.*}}) #[[EXPBF:[0-9]+]]
  %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %sub0)
; CHECK-NEXT: %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %{{.*}}) #[[EXPBF:[0-9]+]]
  %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %sub1)
  %sum = fadd fast half %exp0, %exp1
  store half %sum, ptr addrspace(1) %output, align 2
  ret void
}

define amdgpu_kernel void @kernel_f16(ptr addrspace(1) %input, ptr addrspace(1) %scales, ptr addrspace(1) %output) {
entry:
  %in0 = load half, ptr addrspace(1) %input, align 2
  %ptr1 = getelementptr half, ptr addrspace(1) %input, i64 1
  %in1 = load half, ptr addrspace(1) %ptr1, align 2
  %scale0 = load half, ptr addrspace(1) %scales, align 2
  %sptr1 = getelementptr half, ptr addrspace(1) %scales, i64 1
  %scale1 = load half, ptr addrspace(1) %sptr1, align 2
  %mul0 = fmul contract half %in0, 0xH3E14
  %mul1 = fmul contract half %in1, 0xH3E14
  %sub0 = fsub contract half %mul0, %scale0
  %sub1 = fsub contract half %mul1, %scale1
; CHECK: %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %{{.*}}) #[[EXPBF:[0-9]+]]
  %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %sub0)
; CHECK-NEXT: %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %{{.*}}) #[[EXPBF:[0-9]+]]
  %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %sub1)
; CHECK-NEXT: %log0 = tail call half @llvm.amdgcn.log.f16(half %{{.*}}) #[[LOGBF:[0-9]+]]
  %log0 = tail call half @llvm.amdgcn.log.f16(half %exp0)
; CHECK-NEXT: %log1 = tail call half @llvm.amdgcn.log.f16(half %{{.*}}) #[[LOGBF:[0-9]+]]
  %log1 = tail call half @llvm.amdgcn.log.f16(half %exp1)
  %sum = fadd fast half %log0, %log1
  store half %sum, ptr addrspace(1) %output, align 2
  ret void
}

define amdgpu_kernel void @reuse_shuffle(
  ptr addrspace(1) noalias %input, ptr addrspace(1) noalias %scales,
  ptr addrspace(1) noalias %output) {
entry:
  %iptr1 = getelementptr half, ptr addrspace(1) %input, i64 1
  %sptr1 = getelementptr half, ptr addrspace(1) %scales, i64 1
  %optr1 = getelementptr half, ptr addrspace(1) %output, i64 1
  %optr2 = getelementptr half, ptr addrspace(1) %output, i64 2
  %optr3 = getelementptr half, ptr addrspace(1) %output, i64 3

  %in0 = load half, ptr addrspace(1) %input, align 2
  %in1 = load half, ptr addrspace(1) %iptr1, align 2
  %s0 = load half, ptr addrspace(1) %scales, align 2
  %s1 = load half, ptr addrspace(1) %sptr1, align 2

  %add0 = fadd contract half %in0, 0xH3E14
  %add1 = fadd contract half %in1, 0xH3E14

  %mul0 = fmul contract half %add0, %s0
  %mul1 = fmul contract half %add1, %s1

; CHECK: %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %{{.*}}) #[[EXPBF:[0-9]+]]
  %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %mul0)
; CHECK-NEXT: %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %{{.*}}) #[[EXPBF:[0-9]+]]
  %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %mul1)

  store half %exp0, ptr addrspace(1) %output, align 2
  store half %exp1, ptr addrspace(1) %optr1, align 2
  store half %exp1, ptr addrspace(1) %optr2, align 2
  store half %exp1, ptr addrspace(1) %optr3, align 2
  ret void
}

declare half @llvm.amdgcn.exp2.f16(half)
declare float @llvm.amdgcn.exp2.f32(float)
declare <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(i32 immarg, <16 x i32>, i32 immarg, <16 x i32>, i16 immarg, <8 x float>, i32 immarg, i32 immarg, i32, i32 immarg, i32 immarg, i32, i1 immarg, i1 immarg)


; CHECK-LABEL: define dso_local <2 x float> @amdgcn_vrs2_exp2_f32(<2 x float> %0)
; CHECK-LABEL: {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[TMP:%.*]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[TMP:%.*]], i32 1 
; CHECK-NEXT:    [[EXP1:%.*]] = call float @llvm.amdgcn.exp2.f32(float [[TMP1]])
; CHECK-NEXT:    [[EXP2:%.*]] = call float @llvm.amdgcn.exp2.f32(float [[TMP2]])
; CHECK-NEXT:    [[VEC1:%.*]] = insertelement <2 x float> poison, float [[EXP1]], i32 0
; CHECK-NEXT:    [[VEC2:%.*]] = insertelement <2 x float> [[VEC1]], float [[EXP2]], i32 1
; CHECK-NEXT:    ret <2 x float> [[VEC2]]
; CHECK-LABEL: }
;
; CHECK-LABEL: define dso_local <2 x float> @amdgcn_vrs2_log_f32(<2 x float> %0)
; CHECK-LABEL: {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[TMP:%.*]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[TMP:%.*]], i32 1 
; CHECK-NEXT:    [[EXP1:%.*]] = call float @llvm.amdgcn.log.f32(float [[TMP1]])
; CHECK-NEXT:    [[EXP2:%.*]] = call float @llvm.amdgcn.log.f32(float [[TMP2]])
; CHECK-NEXT:    [[VEC1:%.*]] = insertelement <2 x float> poison, float [[EXP1]], i32 0
; CHECK-NEXT:    [[VEC2:%.*]] = insertelement <2 x float> [[VEC1]], float [[EXP2]], i32 1
; CHECK-NEXT:    ret <2 x float> [[VEC2]]
; CHECK-LABEL: }
; CHECK-LABEL: define dso_local <2 x half> @amdgcn_vrs2_exp2_f16(
; CHECK-LABEL: {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x half> [[TMP:%.*]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x half> [[TMP:%.*]], i32 1 
; CHECK-NEXT:    [[EXP1:%.*]] = call half @llvm.amdgcn.exp2.f16(half [[TMP1]])
; CHECK-NEXT:    [[EXP2:%.*]] = call half @llvm.amdgcn.exp2.f16(half [[TMP2]])
; CHECK-NEXT:    [[VEC1:%.*]] = insertelement <2 x half> poison, half [[EXP1]], i32 0
; CHECK-NEXT:    [[VEC2:%.*]] = insertelement <2 x half> [[VEC1]], half [[EXP2]], i32 1
; CHECK-NEXT:    ret <2 x half> [[VEC2]]
; CHECK-LABEL: }
; CHECK-LABEL: define dso_local <2 x half> @amdgcn_vrs2_log_f16(
; CHECK-LABEL: {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x half> [[TMP:%.*]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x half> [[TMP:%.*]], i32 1 
; CHECK-NEXT:    [[EXP1:%.*]] = call half @llvm.amdgcn.log.f16(half [[TMP1]])
; CHECK-NEXT:    [[EXP2:%.*]] = call half @llvm.amdgcn.log.f16(half [[TMP2]])
; CHECK-NEXT:    [[VEC1:%.*]] = insertelement <2 x half> poison, half [[EXP1]], i32 0
; CHECK-NEXT:    [[VEC2:%.*]] = insertelement <2 x half> [[VEC1]], half [[EXP2]], i32 1
; CHECK-NEXT:    ret <2 x half> [[VEC2]]
; CHECK-LABEL: }

; CHECK:      attributes #[[EXPF]] = { "vector-function-abi-variant"=
; CHECK-SAME:   "_ZGV_LLVM_N2v_llvm.amdgcn.exp2.f32(amdgcn_vrs2_exp2_f32)" }

; CHECK:      attributes #[[LOGF]] = { "vector-function-abi-variant"=
; CHECK-SAME:   "_ZGV_LLVM_N2v_llvm.amdgcn.log.f32(amdgcn_vrs2_log_f32)" }

; CHECK:      attributes #[[EXPBF]] = { "vector-function-abi-variant"=
; CHECK-SAME:   "_ZGV_LLVM_N2v_llvm.amdgcn.exp2.f16(amdgcn_vrs2_exp2_f16)" }

; CHECK:      attributes #[[LOGBF]] = { "vector-function-abi-variant"=
; CHECK-SAME:   "_ZGV_LLVM_N2v_llvm.amdgcn.log.f16(amdgcn_vrs2_log_f16)" }
