; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=inject-tli-mappings,slp-vectorizer -S -mcpu=gfx1250 -mtriple=amdgcn-amd-amdhsa  -vector-library=AMDGCNLIB  -o - %s | FileCheck %s
target triple = "amdgcn-amd-amdhsa"

define amdgpu_kernel void @test_with_wmma( ptr addrspace(1) %input, ptr addrspace(1) %output, float %scaled_max, <16 x i32> %A, <16 x i32> %B, i32 %scale_idx) {
; CHECK-LABEL: define amdgpu_kernel void @test_with_wmma(
; CHECK-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[OUTPUT:%.*]], float [[SCALED_MAX:%.*]], <16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SCALE_IDX:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr addrspace(1) [[INPUT]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = fmul contract <2 x float> [[TMP0]], splat (float 0x3FC0527DC0000000)
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x float> poison, float [[SCALED_MAX]], i32 0
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <2 x float> [[TMP2]], <2 x float> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = fsub contract <2 x float> [[TMP1]], [[TMP3]]
; CHECK-NEXT:    [[EXP:%.*]] = call <2 x float> @amdgcn_vrs2_exp2_f32(<2 x float> [[TMP4]])
; CHECK-NEXT:    [[VEC_I32:%.*]] = bitcast <2 x float> [[EXP]] to <2 x i32>
; CHECK-NEXT:    [[SCALE0:%.*]] = extractelement <2 x i32> [[VEC_I32]], i64 0
; CHECK-NEXT:    [[SCALE1:%.*]] = extractelement <2 x i32> [[VEC_I32]], i64 1
; CHECK-NEXT:    [[WMMA0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(i32 0, <16 x i32> [[A]], i32 0, <16 x i32> [[B]], i16 0, <8 x float> zeroinitializer, i32 0, i32 0, i32 [[SCALE0]], i32 0, i32 0, i32 [[SCALE_IDX]], i1 false, i1 false)
; CHECK-NEXT:    [[WMMA1:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(i32 0, <16 x i32> [[A]], i32 0, <16 x i32> [[B]], i16 0, <8 x float> [[WMMA0]], i32 0, i32 0, i32 [[SCALE1]], i32 0, i32 0, i32 [[SCALE_IDX]], i1 false, i1 false)
; CHECK-NEXT:    store <8 x float> [[WMMA1]], ptr addrspace(1) [[OUTPUT]], align 32
; CHECK-NEXT:    ret void
;
entry:

  %in0 = load float, ptr addrspace(1) %input, align 4
  %ptr1 = getelementptr float, ptr addrspace(1) %input, i64 1
  %in1 = load float, ptr addrspace(1) %ptr1, align 4

  %mul0 = fmul contract float %in0, 0x3FC0527DC0000000
  %mul1 = fmul contract float %in1, 0x3FC0527DC0000000

  %sub0 = fsub contract float %mul0, %scaled_max
  %sub1 = fsub contract float %mul1, %scaled_max

  %exp0 = tail call float @llvm.amdgcn.exp2.f32(float %sub0)
  %exp1 = tail call float @llvm.amdgcn.exp2.f32(float %sub1)

  %vec0 = insertelement <2 x float> poison, float %exp0, i64 0
  %vec1 = insertelement <2 x float> %vec0, float %exp1, i64 1

  %vec_i32 = bitcast <2 x float> %vec1 to <2 x i32>

  %scale0 = extractelement <2 x i32> %vec_i32, i64 0
  %scale1 = extractelement <2 x i32> %vec_i32, i64 1

  %wmma0 = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(
  i32 0, <16 x i32> %A, i32 0, <16 x i32> %B, i16 0, <8 x float> zeroinitializer,
  i32 0, i32 0, i32 %scale0, i32 0, i32 0, i32 %scale_idx, i1 false, i1 false)

  %wmma1 = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(
  i32 0, <16 x i32> %A, i32 0, <16 x i32> %B, i16 0, <8 x float> %wmma0,
  i32 0, i32 0, i32 %scale1, i32 0, i32 0, i32 %scale_idx, i1 false, i1 false)

  store <8 x float> %wmma1, ptr addrspace(1) %output, align 32
  ret void
}

define amdgpu_kernel void @test_amdgcn_exp_log(ptr addrspace(1) %input, ptr addrspace(1) %scales, ptr addrspace(1) %output) {
; CHECK-LABEL: define amdgpu_kernel void @test_amdgcn_exp_log(
; CHECK-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[SCALES:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr addrspace(1) [[INPUT]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x float>, ptr addrspace(1) [[SCALES]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = fmul contract <2 x float> [[TMP0]], splat (float 0x3FC0527DC0000000)
; CHECK-NEXT:    [[TMP3:%.*]] = fsub contract <2 x float> [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[EXP:%.*]] = call <2 x float> @amdgcn_vrs2_exp2_f32(<2 x float> [[TMP3]])
; CHECK-NEXT:    [[LOG:%.*]] = call <2 x float> @amdgcn_vrs2_log_f32(<2 x float> [[EXP]])
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x float> [[LOG]], i32 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <2 x float> [[LOG]], i32 1
; CHECK-NEXT:    [[SUM:%.*]] = fadd fast float [[TMP12]], [[TMP13]]
; CHECK-NEXT:    store float [[SUM]], ptr addrspace(1) [[OUTPUT]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %in0 = load float, ptr addrspace(1) %input, align 4
  %ptr1 = getelementptr float, ptr addrspace(1) %input, i64 1
  %in1 = load float, ptr addrspace(1) %ptr1, align 4
  %scale0 = load float, ptr addrspace(1) %scales, align 4
  %sptr1 = getelementptr float, ptr addrspace(1) %scales, i64 1
  %scale1 = load float, ptr addrspace(1) %sptr1, align 4
  %mul0 = fmul contract float %in0, 0x3FC0527DC0000000
  %mul1 = fmul contract float %in1, 0x3FC0527DC0000000
  %sub0 = fsub contract float %mul0, %scale0
  %sub1 = fsub contract float %mul1, %scale1
  %exp0 = tail call float @llvm.amdgcn.exp2.f32(float %sub0)
  %log0 = tail call float @llvm.amdgcn.log.f32(float %exp0)
  %exp1 = tail call float @llvm.amdgcn.exp2.f32(float %sub1)
  %log1 = tail call float @llvm.amdgcn.log.f32(float %exp1)
  %sum = fadd fast float %log0, %log1
  store float %sum, ptr addrspace(1) %output, align 4
  ret void
}

define amdgpu_kernel void @test_amdgcn_exp_f16(ptr addrspace(1) %input, ptr addrspace(1) %scales, ptr addrspace(1) %output) {
; CHECK-LABEL: define amdgpu_kernel void @test_amdgcn_exp_f16(
; CHECK-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[SCALES:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x half>, ptr addrspace(1) [[INPUT]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x half>, ptr addrspace(1) [[SCALES]], align 2
; CHECK-NEXT:    [[TMP2:%.*]] = fmul contract <2 x half> [[TMP0]], splat (half 0xH3E14)
; CHECK-NEXT:    [[TMP3:%.*]] = fsub contract <2 x half> [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[EXP:%.*]] = call <2 x half> @amdgcn_vrs2_exp2_f16(<2 x half> [[TMP3]])
; CHECK-NEXT:    [[TMP10:%.*]] = call fast half @llvm.vector.reduce.fadd.v2f16(half 0xH0000, <2 x half> [[EXP]])
; CHECK-NEXT:    store half [[TMP10]], ptr addrspace(1) [[OUTPUT]], align 2
; CHECK-NEXT:    ret void
;
entry:
  %in0 = load half, ptr addrspace(1) %input, align 2
  %ptr1 = getelementptr half, ptr addrspace(1) %input, i64 1
  %in1 = load half, ptr addrspace(1) %ptr1, align 2
  %scale0 = load half, ptr addrspace(1) %scales, align 2
  %sptr1 = getelementptr half, ptr addrspace(1) %scales, i64 1
  %scale1 = load half, ptr addrspace(1) %sptr1, align 2
  %mul0 = fmul contract half %in0, 0xH3E14
  %mul1 = fmul contract half %in1, 0xH3E14
  %sub0 = fsub contract half %mul0, %scale0
  %sub1 = fsub contract half %mul1, %scale1
  %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %sub0)
  %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %sub1)
  %sum = fadd fast half %exp0, %exp1
  store half %sum, ptr addrspace(1) %output, align 2
  ret void
}

define amdgpu_kernel void @kernel_f16(ptr addrspace(1) %input, ptr addrspace(1) %scales, ptr addrspace(1) %output) {
; CHECK-LABEL: define amdgpu_kernel void @kernel_f16(
; CHECK-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[SCALES:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x half>, ptr addrspace(1) [[INPUT]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x half>, ptr addrspace(1) [[SCALES]], align 2
; CHECK-NEXT:    [[TMP2:%.*]] = fmul contract <2 x half> [[TMP0]], splat (half 0xH3E14)
; CHECK-NEXT:    [[TMP3:%.*]] = fsub contract <2 x half> [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[EXP:%.*]] = call <2 x half> @amdgcn_vrs2_exp2_f16(<2 x half> [[TMP3]])
; CHECK-NEXT:    [[LOG:%.*]] = call <2 x half> @amdgcn_vrs2_log_f16(<2 x half> [[EXP]])
; CHECK-NEXT:    [[SUM:%.*]] = call fast half @llvm.vector.reduce.fadd.v2f16(half 0xH0000, <2 x half> [[LOG]])
; CHECK-NEXT:    store half [[SUM]], ptr addrspace(1) [[OUTPUT]], align 2
; CHECK-NEXT:    ret void
;
entry:
  %in0 = load half, ptr addrspace(1) %input, align 2
  %ptr1 = getelementptr half, ptr addrspace(1) %input, i64 1
  %in1 = load half, ptr addrspace(1) %ptr1, align 2
  %scale0 = load half, ptr addrspace(1) %scales, align 2
  %sptr1 = getelementptr half, ptr addrspace(1) %scales, i64 1
  %scale1 = load half, ptr addrspace(1) %sptr1, align 2
  %mul0 = fmul contract half %in0, 0xH3E14
  %mul1 = fmul contract half %in1, 0xH3E14
  %sub0 = fsub contract half %mul0, %scale0
  %sub1 = fsub contract half %mul1, %scale1
  %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %sub0)
  %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %sub1)
  %log0 = tail call half @llvm.amdgcn.log.f16(half %exp0)
  %log1 = tail call half @llvm.amdgcn.log.f16(half %exp1)
  %sum = fadd fast half %log0, %log1
  store half %sum, ptr addrspace(1) %output, align 2
  ret void
}

define amdgpu_kernel void @reuse_shuffle(
; CHECK-LABEL: define amdgpu_kernel void @reuse_shuffle(
; CHECK-SAME: ptr addrspace(1) noalias [[INPUT:%.*]], ptr addrspace(1) noalias [[SCALES:%.*]], ptr addrspace(1) noalias [[OUTPUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x half>, ptr addrspace(1) [[INPUT]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x half>, ptr addrspace(1) [[SCALES]], align 2
; CHECK-NEXT:    [[TMP8:%.*]] = fadd contract <2 x half> [[TMP0]], splat (half 0xH3E14)
; CHECK-NEXT:    [[TMP10:%.*]] = fmul contract <2 x half> [[TMP8]], [[TMP1]]
; CHECK-NEXT:    [[EXP:%.*]] = call <2 x half> @amdgcn_vrs2_exp2_f16(<2 x half> [[TMP10]])
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x half> [[EXP]], <2 x half> poison, <4 x i32> <i32 0, i32 1, i32 1, i32 1>
; CHECK-NEXT:    store <4 x half> [[TMP9]], ptr addrspace(1) [[OUTPUT]], align 2
; CHECK-NEXT:    ret void
;
;
  ptr addrspace(1) noalias %input, ptr addrspace(1) noalias %scales,
  ptr addrspace(1) noalias %output) {
entry:
  %iptr1 = getelementptr half, ptr addrspace(1) %input, i64 1
  %sptr1 = getelementptr half, ptr addrspace(1) %scales, i64 1
  %optr1 = getelementptr half, ptr addrspace(1) %output, i64 1
  %optr2 = getelementptr half, ptr addrspace(1) %output, i64 2
  %optr3 = getelementptr half, ptr addrspace(1) %output, i64 3

  %in0 = load half, ptr addrspace(1) %input, align 2
  %in1 = load half, ptr addrspace(1) %iptr1, align 2
  %s0 = load half, ptr addrspace(1) %scales, align 2
  %s1 = load half, ptr addrspace(1) %sptr1, align 2

  %add0 = fadd contract half %in0, 0xH3E14
  %add1 = fadd contract half %in1, 0xH3E14

  %mul0 = fmul contract half %add0, %s0
  %mul1 = fmul contract half %add1, %s1

  %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %mul0)
  %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %mul1)

  store half %exp0, ptr addrspace(1) %output, align 2
  store half %exp1, ptr addrspace(1) %optr1, align 2
  store half %exp1, ptr addrspace(1) %optr2, align 2
  store half %exp1, ptr addrspace(1) %optr3, align 2
  ret void
}

declare half @llvm.amdgcn.exp2.f16(half)
declare float @llvm.amdgcn.exp2.f32(float)
declare <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(i32 immarg, <16 x i32>, i32 immarg, <16 x i32>, i16 immarg, <8 x float>, i32 immarg, i32 immarg, i32, i32 immarg, i32 immarg, i32, i1 immarg, i1 immarg)
